export { puzzles };

var PuzzleType = {
    Swap: 0,
    Rotate: 1,
}

const puzzles = {
    "2024-03-08": { 
        id: 1,
        image: "1.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-09": { 
        id: 2,
        image: "2.gif",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-10": { 
        id: 3,
        image: "3.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-11": { 
        id: 4,
        image: "4.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-12": { 
        id: 5,
        image: "5.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-13": { 
        id: 6,
        image: "6.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-14": { 
        id: 7,
        image: "7.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-15": { 
        id: 8,
        image: "8.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-16": { 
        id: 9,
        image: "9.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-17": { 
        id: 10,
        image: "10.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },    
    "2024-03-18": { 
        id: 11,
        image: "11.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-19": { 
        id: 12,
        image: "12.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-20": { 
        id: 13,
        image: "13.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-21": { 
        id: 14,
        image: "14.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-22": { 
        id: 15,
        image: "15.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-23": { 
        id: 16,
        image: "16.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-24": { 
        id: 17,
        image: "17.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-25": { 
        id: 18,
        image: "18.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-26": { 
        id: 19,
        image: "19.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-27": { 
        id: 20,
        image: "20.jpg",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },
    "2024-03-28": { 
        id: 21,
        image: "21.gif",
        type: PuzzleType.Swap,
        seed: 12345,
        author: "author",
        desc: "desc",
    },

};

